mutation createBoardCard($input: CreateCardInput!) {
  card {
    createCard(input: $input) {
      ok
      card {
        id
        title
        description
        columnId
        boardId
      }
      error {
        message
      }
    }
  }
}

mutation updateBoardCard($input: UpdateCardInput!) {
  card {
    updateCard(input: $input) {
      ok
      card {
        id
        title
        order
        description
        columnId
        boardId
      }
      error {
        message
      }
    }
  }
}

mutation deleteBoardCard($input: DeleteCardInput!) {
  card {
    deleteCard(input: $input) {
      ok
      cardId
      error {
        message
      }
    }
  }
}

query getUserCards {
  me {
    cards {
      id
      title
      description
    }
    boards {
      id
      columns {
        id
        title
        cards {
          id
          title
          description
        }
      }
    }
  }
}
