mutation createBoardCard($input: CreateCardInput!) {
  card {
    createCard(input: $input) {
      ok
      # card {
      #   id
      #   # title
      #   # columnId
      #   # boardId
      # }
      error {
        message
      }
    }
  }
}

query getUserCards {
  me {
    cards {
      id
      title
    }
    boards {
      id
      columns {
        id
        title
        cards {
          id
          title
        }
      }
    }
  }
}
